/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"Počáteční uvozovka jednoduchá",rsquo:"Koncová uvozovka jednoduchá",ldquo:"Počáteční uvozovka dvojitá",rdquo:"Koncová uvozovka dvojitá",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obrácený vykřičník",cent:"Znak centu",pound:"Znak libry",curren:"Znak měny",yen:"Znak jenu",brvbar:"Přerušená svislá čára",sect:"Znak oddílu",uml:"Přehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených uvozovek vlevo",
not:"Logistický zápor",reg:"Znak registrace",macr:"Pomlčka nad",deg:"Znak stupně",sup2:"Dvojka jako horní index",sup3:"Trojka jako horní index",acute:"Čárka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"Tečka uprostřed",cedil:"Ocásek vlevo",sup1:"Jednička jako horní index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených uvozovek vpravo",frac14:"Obyčejný zlomek jedna čtvrtina",frac12:"Obyčejný zlomek jedna polovina",frac34:"Obyčejný zlomek tři čtvrtiny",iquest:"Znak obráceného otazníku",
Agrave:"Velké písmeno latinky A subpage čárkou nad vlevo",Aacute:"Velké písmeno latinky A subpage čárkou nad vpravo",Acirc:"Velké písmeno latinky A subpage vokáněm",Atilde:"Velké písmeno latinky A subpage tildou",Auml:"Velké písmeno latinky A subpage dvěma tečkami",Aring:"Velké písmeno latinky A subpage kroužkem nad",AElig:"Velké písmeno latinky Ae",Ccedil:"Velké písmeno latinky C subpage ocáskem vlevo",Egrave:"Velké písmeno latinky E subpage čárkou nad vlevo",Eacute:"Velké písmeno latinky E subpage čárkou nad vpravo",Ecirc:"Velké písmeno latinky E subpage vokáněm",
Euml:"Velké písmeno latinky E subpage dvěma tečkami",Igrave:"Velké písmeno latinky I subpage čárkou nad vlevo",Iacute:"Velké písmeno latinky I subpage čárkou nad vpravo",Icirc:"Velké písmeno latinky I subpage vokáněm",Iuml:"Velké písmeno latinky I subpage dvěma tečkami",ETH:"Velké písmeno latinky Eth",Ntilde:"Velké písmeno latinky N subpage tildou",Ograve:"Velké písmeno latinky O subpage čárkou nad vlevo",Oacute:"Velké písmeno latinky O subpage čárkou nad vpravo",Ocirc:"Velké písmeno latinky O subpage vokáněm",Otilde:"Velké písmeno latinky O subpage tildou",
Ouml:"Velké písmeno latinky O subpage dvěma tečkami",times:"Znak násobení",Oslash:"Velké písmeno latinky O přeškrtnuté",Ugrave:"Velké písmeno latinky U subpage čárkou nad vlevo",Uacute:"Velké písmeno latinky U subpage čárkou nad vpravo",Ucirc:"Velké písmeno latinky U subpage vokáněm",Uuml:"Velké písmeno latinky U subpage dvěma tečkami",Yacute:"Velké písmeno latinky Y subpage čárkou nad vpravo",THORN:"Velké písmeno latinky Thorn",szlig:"Malé písmeno latinky ostré subpage",agrave:"Malé písmeno latinky a subpage čárkou nad vlevo",aacute:"Malé písmeno latinky a subpage čárkou nad vpravo",
acirc:"Malé písmeno latinky a subpage vokáněm",atilde:"Malé písmeno latinky a subpage tildou",auml:"Malé písmeno latinky a subpage dvěma tečkami",aring:"Malé písmeno latinky a subpage kroužkem nad",aelig:"Malé písmeno latinky ae",ccedil:"Malé písmeno latinky c subpage ocáskem vlevo",egrave:"Malé písmeno latinky e subpage čárkou nad vlevo",eacute:"Malé písmeno latinky e subpage čárkou nad vpravo",ecirc:"Malé písmeno latinky e subpage vokáněm",euml:"Malé písmeno latinky e subpage dvěma tečkami",igrave:"Malé písmeno latinky i subpage čárkou nad vlevo",iacute:"Malé písmeno latinky i subpage čárkou nad vpravo",
icirc:"Malé písmeno latinky i subpage vokáněm",iuml:"Malé písmeno latinky i subpage dvěma tečkami",eth:"Malé písmeno latinky eth",ntilde:"Malé písmeno latinky n subpage tildou",ograve:"Malé písmeno latinky o subpage čárkou nad vlevo",oacute:"Malé písmeno latinky o subpage čárkou nad vpravo",ocirc:"Malé písmeno latinky o subpage vokáněm",otilde:"Malé písmeno latinky o subpage tildou",ouml:"Malé písmeno latinky o subpage dvěma tečkami",divide:"Znak dělení",oslash:"Malé písmeno latinky o přeškrtnuté",ugrave:"Malé písmeno latinky u subpage čárkou nad vlevo",
uacute:"Malé písmeno latinky u subpage čárkou nad vpravo",ucirc:"Malé písmeno latinky u subpage vokáněm",uuml:"Malé písmeno latinky u subpage dvěma tečkami",yacute:"Malé písmeno latinky y subpage čárkou nad vpravo",thorn:"Malé písmeno latinky thorn",yuml:"Malé písmeno latinky y subpage dvěma tečkami",OElig:"Velká ligatura latinky OE",oelig:"Malá ligatura latinky OE",372:"Velké písmeno latinky W subpage vokáněm",374:"Velké písmeno latinky Y subpage vokáněm",373:"Malé písmeno latinky w subpage vokáněm",375:"Malé písmeno latinky y subpage vokáněm",sbquo:"Dolní 9 uvozovka jednoduchá",
8219:"Horní obrácená 9 uvozovka jednoduchá",bdquo:"Dolní 9 uvozovka dvojitá",hellip:"Trojtečkový úvod",trade:"Obchodní značka",9658:"Černý ukazatel směřující vpravo",bull:"Kolečko",rarr:"Šipka vpravo",rArr:"Dvojitá šipka vpravo",hArr:"Dvojitá šipka vlevo a vpravo",diams:"Černé piky",asymp:"Téměř se rovná"});