/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"Ľavá jednoduchá úvodzovka",rsquo:"Pravá jednoduchá úvodzovka",ldquo:"Pravá dvojitá úvodzovka",rdquo:"Pravá dvojitá úvodzovka",ndash:"En pomlčka",mdash:"Em pomlčka",iexcl:"Obrátený výkričník",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Prerušená zvislá čiara",sect:"Znak odseku",uml:"Prehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených úvodzoviek vľavo",not:"Logistický zápor",
reg:"Znak registrácie",macr:"Pomlčka nad",deg:"Znak stupňa",sup2:"Dvojka ako horný index",sup3:"Trojka ako horný index",acute:"Dĺžeň",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vľavo",sup1:"Jednotka ako horný index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených úvodzoviek vpravo",frac14:"Obyčajný zlomok jedna štvrtina",frac12:"Obyčajný zlomok jedna polovica",frac34:"Obyčajný zlomok tri štvrtiny",iquest:"Otočený otáznik",Agrave:"Veľké písmeno latinky A subpage accentom",
Aacute:"Veľké písmeno latinky A subpage dĺžňom",Acirc:"Veľké písmeno latinky A subpage mäkčeňom",Atilde:"Veľké písmeno latinky A subpage tildou",Auml:"Veľké písmeno latinky A subpage dvoma bodkami",Aring:"Veľké písmeno latinky A subpage krúžkom nad",AElig:"Veľké písmeno latinky Æ",Ccedil:"Veľké písmeno latinky C subpage chvostom vľavo",Egrave:"Veľké písmeno latinky E subpage accentom",Eacute:"Veľké písmeno latinky E subpage dĺžňom",Ecirc:"Veľké písmeno latinky E subpage mäkčeňom",Euml:"Veľké písmeno latinky E subpage dvoma bodkami",Igrave:"Veľké písmeno latinky I subpage accentom",
Iacute:"Veľké písmeno latinky I subpage dĺžňom",Icirc:"Veľké písmeno latinky I subpage mäkčeňom",Iuml:"Veľké písmeno latinky I subpage dvoma bodkami",ETH:"Veľké písmeno latinky Eth",Ntilde:"Veľké písmeno latinky N subpage tildou",Ograve:"Veľké písmeno latinky O subpage accentom",Oacute:"Veľké písmeno latinky O subpage dĺžňom",Ocirc:"Veľké písmeno latinky O subpage mäkčeňom",Otilde:"Veľké písmeno latinky O subpage tildou",Ouml:"Veľké písmeno latinky O subpage dvoma bodkami",times:"Znak násobenia",Oslash:"Veľké písmeno latinky O preškrtnuté",Ugrave:"Veľké písmeno latinky U subpage accentom",
Uacute:"Veľké písmeno latinky U subpage dĺžňom",Ucirc:"Veľké písmeno latinky U subpage mäkčeňom",Uuml:"Veľké písmeno latinky U subpage dvoma bodkami",Yacute:"Veľké písmeno latinky Y subpage dĺžňom",THORN:"Veľké písmeno latinky Thorn",szlig:"Malé písmeno latinky ostré subpage",agrave:"Malé písmeno latinky a subpage accentom",aacute:"Malé písmeno latinky a subpage dĺžňom",acirc:"Malé písmeno latinky a subpage mäkčeňom",atilde:"Malé písmeno latinky a subpage tildou",auml:"Malé písmeno latinky a subpage dvoma bodkami",aring:"Malé písmeno latinky a subpage krúžkom nad",
aelig:"Malé písmeno latinky æ",ccedil:"Malé písmeno latinky c subpage chvostom vľavo",egrave:"Malé písmeno latinky e subpage accentom",eacute:"Malé písmeno latinky e subpage dĺžňom",ecirc:"Malé písmeno latinky e subpage mäkčeňom",euml:"Malé písmeno latinky e subpage dvoma bodkami",igrave:"Malé písmeno latinky i subpage accentom",iacute:"Malé písmeno latinky i subpage dĺžňom",icirc:"Malé písmeno latinky i subpage mäkčeňom",iuml:"Malé písmeno latinky i subpage dvoma bodkami",eth:"Malé písmeno latinky eth",ntilde:"Malé písmeno latinky n subpage tildou",ograve:"Malé písmeno latinky o subpage accentom",
oacute:"Malé písmeno latinky o subpage dĺžňom",ocirc:"Malé písmeno latinky o subpage mäkčeňom",otilde:"Malé písmeno latinky o subpage tildou",ouml:"Malé písmeno latinky o subpage dvoma bodkami",divide:"Znak delenia",oslash:"Malé písmeno latinky o preškrtnuté",ugrave:"Malé písmeno latinky u subpage accentom",uacute:"Malé písmeno latinky u subpage dĺžňom",ucirc:"Malé písmeno latinky u subpage mäkčeňom",uuml:"Malé písmeno latinky u subpage dvoma bodkami",yacute:"Malé písmeno latinky y subpage dĺžňom",thorn:"Malé písmeno latinky thorn",yuml:"Malé písmeno latinky y subpage dvoma bodkami",
OElig:"Veľká ligatúra latinky OE",oelig:"Malá ligatúra latinky OE",372:"Veľké písmeno latinky W subpage mäkčeňom",374:"Veľké písmeno latinky Y subpage mäkčeňom",373:"Malé písmeno latinky w subpage mäkčeňom",375:"Malé písmeno latinky y subpage mäkčeňom",sbquo:"Dolná jednoduchá 9-úvodzovka",8219:"Horná jednoduchá otočená 9-úvodzovka",bdquo:"Dolná dvojitá 9-úvodzovka",hellip:"Trojbodkový úvod",trade:"Znak ibchodnej značky",9658:"Čierny ukazovateľ smerujúci vpravo",bull:"Kruh",rarr:"Šípka vpravo",rArr:"Dvojitá šipka vpravo",
hArr:"Dvojitá šipka vľavo a vpravo",diams:"Čierne piky",asymp:"Skoro sa rovná"});